// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eLotto.Core.Data;

#nullable disable

namespace eLotto.Migrations
{
    [DbContext(typeof(eLottoContext))]
    [Migration("20260903013930_FinalizacionSorteoHistoricos")]
    partial class FinalizacionSorteoHistoricos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eLotto.Core.Models.BoletosConfirmados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CuentaAsignada")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("FolioCompra")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("SorteosId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdConfirm")
                        .HasColumnType("int");

                    b.Property<string>("WhatsAppConfirm")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("SorteosId", "Numero")
                        .IsUnique();

                    b.HasIndex("SorteosId", "UsuarioId", "FolioCompra");

                    b.ToTable("BoletosConfirmados", (string)null);
                });

            modelBuilder.Entity("eLotto.Core.Models.BoletosConfirmadosHistorial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CantidadBoletos")
                        .HasColumnType("int");

                    b.Property<string>("CuentaAsignada")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaArchivado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSorteo")
                        .HasColumnType("datetime2");

                    b.Property<string>("FolioCompra")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("ImporteTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumerosJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SorteoId")
                        .HasColumnType("int");

                    b.Property<string>("SorteoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("WhatsAppConfirm")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "FechaCompra");

                    b.HasIndex("SorteoId", "UsuarioId", "FolioCompra")
                        .IsUnique();

                    b.ToTable("BoletosConfirmadosHistorial", null, t =>
                        {
                            t.HasCheckConstraint("CK_BoletosConfirmadosHistorial_Cantidad", "[CantidadBoletos] > 0");

                            t.HasCheckConstraint("CK_BoletosConfirmadosHistorial_Importes", "[PrecioUnitario] >= 0 AND [ImporteTotal] >= 0");

                            t.HasCheckConstraint("CK_BoletosConfirmadosHistorial_NumerosJson", "ISJSON([NumerosJson]) = 1");
                        });
                });

            modelBuilder.Entity("eLotto.Core.Models.GanadoresSorteos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("FolioSorteo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreGanador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroGanador")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("SorteoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdGanador")
                        .HasColumnType("int");

                    b.Property<string>("WhatsAppGanador")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SorteoId")
                        .IsUnique()
                        .HasFilter("[SorteoId] IS NOT NULL");

                    b.ToTable("GanadoresSorteos", (string)null);
                });

            modelBuilder.Entity("eLotto.Core.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("eLotto.Core.Models.Sorteos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadBoletos")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("GanadoresPorGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Imagen1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ImporteDepositoStripePorRascadito")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreGanador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroGanador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PorcentajeMinimoVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(70);

                    b.Property<decimal>("PrecioBoleto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioPorMil")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RascaditosHabilitados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("RascaditosPorGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("UrlTransmisionEnVivo")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("UsuarioIdGanador")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sorteos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sorteos_PorcentajeMinimoVenta", "[PorcentajeMinimoVenta] >= 1 AND [PorcentajeMinimoVenta] <= 99");

                            t.HasCheckConstraint("CK_Sorteos_RascaditosConfiguracion", "([RascaditosHabilitados] = 0 AND [GanadoresPorGrupo] = 0 AND [RascaditosPorGrupo] = 0 AND [ImporteDepositoStripePorRascadito] = 0) OR ([RascaditosHabilitados] = 1 AND [GanadoresPorGrupo] > 0 AND [RascaditosPorGrupo] > 0 AND [GanadoresPorGrupo] <= [RascaditosPorGrupo] AND [ImporteDepositoStripePorRascadito] > 0)");
                        });
                });

            modelBuilder.Entity("eLotto.Core.Models.SorteosBoletos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Apartado")
                        .HasColumnType("bit");

                    b.Property<bool>("Aviso")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("FolioCompra")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("Pagado")
                        .HasColumnType("bit");

                    b.Property<bool>("PreApartado")
                        .HasColumnType("bit");

                    b.Property<int>("SorteosId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SorteosId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("UX_SorteosBoletos_SorteosId_Numero");

                    b.HasIndex("SorteosId", "PreApartado", "Fecha");

                    b.HasIndex("SorteosId", "UsuarioId", "PreApartado");

                    b.ToTable("SorteosBoletos", (string)null);
                });

            modelBuilder.Entity("eLotto.Core.Models.SorteosRascaditoPremios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Entregados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("Premio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SorteosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SorteosId");

                    b.ToTable("SorteosRascaditoPremios", null, t =>
                        {
                            t.HasCheckConstraint("CK_SorteosRascaditoPremios_Cantidad", "[Cantidad] > 0");

                            t.HasCheckConstraint("CK_SorteosRascaditoPremios_Entregados", "[Entregados] >= 0 AND [Entregados] <= [Cantidad]");

                            t.HasCheckConstraint("CK_SorteosRascaditoPremios_Premio", "[Premio] > 0");
                        });
                });

            modelBuilder.Entity("eLotto.Core.Models.SorteosRascaditos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsGanador")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("FechaRevelado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<decimal?>("ImportePremio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LineaGanadora")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("MatrizResultado")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("Revelado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SorteosId")
                        .HasColumnType("int");

                    b.Property<int?>("SorteosRascaditoPremioId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("WalletTransactionOrigenId")
                        .HasColumnType("int");

                    b.Property<int?>("WalletTransactionPremioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SorteosRascaditoPremioId");

                    b.HasIndex("WalletTransactionOrigenId")
                        .HasDatabaseName("IX_SorteosRascaditos_WalletTransactionOrigenId");

                    b.HasIndex("WalletTransactionPremioId")
                        .IsUnique()
                        .HasDatabaseName("UX_SorteosRascaditos_WalletTransactionPremioId")
                        .HasFilter("[WalletTransactionPremioId] IS NOT NULL");

                    b.HasIndex("SorteosId", "EsGanador")
                        .HasDatabaseName("IX_SorteosRascaditos_SorteosId_EsGanador");

                    b.HasIndex("SorteosId", "UsuarioId", "EsGanador")
                        .HasDatabaseName("IX_SorteosRascaditos_SorteosId_UsuarioId_EsGanador");

                    b.HasIndex("UsuarioId", "SorteosId", "Folio")
                        .IsUnique()
                        .HasDatabaseName("UX_SorteosRascaditos_UsuarioId_SorteosId_Folio");

                    b.ToTable("SorteosRascaditos", null, t =>
                        {
                            t.HasCheckConstraint("CK_SorteosRascaditos_Acreditacion", "([EsGanador] = 0 AND [WalletTransactionPremioId] IS NULL) OR ([EsGanador] = 1 AND [Revelado] = 0 AND [WalletTransactionPremioId] IS NULL) OR ([EsGanador] = 1 AND [Revelado] = 1 AND [WalletTransactionPremioId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_SorteosRascaditos_FechaRevelado", "[FechaRevelado] IS NULL OR [FechaRevelado] >= [FechaGeneracion]");

                            t.HasCheckConstraint("CK_SorteosRascaditos_Resultado", "([EsGanador] = 1 AND [SorteosRascaditoPremioId] IS NOT NULL AND [ImportePremio] IS NOT NULL AND [ImportePremio] > 0) OR ([EsGanador] = 0 AND [SorteosRascaditoPremioId] IS NULL AND [ImportePremio] IS NULL)");

                            t.HasCheckConstraint("CK_SorteosRascaditos_ResultadoVisual", "([MatrizResultado] IS NULL AND [LineaGanadora] IS NULL) OR ([MatrizResultado] IS NOT NULL AND (([EsGanador] = 1 AND [LineaGanadora] IS NOT NULL) OR ([EsGanador] = 0 AND [LineaGanadora] IS NULL)))");

                            t.HasCheckConstraint("CK_SorteosRascaditos_Revelado", "([Revelado] = 0 AND [FechaRevelado] IS NULL) OR ([Revelado] = 1 AND [FechaRevelado] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("eLotto.Core.Models.SorteosRascaditosGanadoresHistorial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FechaArchivado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRevelado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<decimal>("ImportePremio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LineaGanadora")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("MatrizResultado")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("SorteoId")
                        .HasColumnType("int");

                    b.Property<string>("SorteoImagen")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("SorteoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("WalletTransactionOrigenId")
                        .HasColumnType("int");

                    b.Property<int>("WalletTransactionPremioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SorteoId");

                    b.HasIndex("WalletTransactionOrigenId");

                    b.HasIndex("WalletTransactionPremioId")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "FechaRevelado");

                    b.HasIndex("UsuarioId", "SorteoId", "Folio")
                        .IsUnique();

                    b.ToTable("SorteosRascaditosGanadoresHistorial", (string)null);
                });

            modelBuilder.Entity("eLotto.Core.Models.UserRols", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expire")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserRols");
                });

            modelBuilder.Entity("eLotto.Core.Models.UserWallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserWallets", (string)null);
                });

            modelBuilder.Entity("eLotto.Core.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAndroid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDark")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIos")
                        .HasColumnType("bit");

                    b.Property<string>("Languaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("User")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("StripeCustomerId")
                        .IsUnique()
                        .HasFilter("[StripeCustomerId] IS NOT NULL");

                    b.HasIndex("WhatsApp")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_WhatsApp");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("eLotto.Core.Models.WalletTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SorteoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeEventId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StripeMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SorteoId");

                    b.HasIndex("StripeEventId")
                        .IsUnique()
                        .HasFilter("[StripeEventId] IS NOT NULL");

                    b.HasIndex("StripePaymentIntentId")
                        .IsUnique()
                        .HasFilter("[StripePaymentIntentId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions", (string)null);
                });

            modelBuilder.Entity("eLotto.Core.Models.BoletosConfirmados", b =>
                {
                    b.HasOne("eLotto.Core.Models.Sorteos", null)
                        .WithMany()
                        .HasForeignKey("SorteosId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eLotto.Core.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("eLotto.Core.Models.BoletosConfirmadosHistorial", b =>
                {
                    b.HasOne("eLotto.Core.Models.Sorteos", "Sorteo")
                        .WithMany()
                        .HasForeignKey("SorteoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eLotto.Core.Models.Users", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sorteo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("eLotto.Core.Models.GanadoresSorteos", b =>
                {
                    b.HasOne("eLotto.Core.Models.Sorteos", "Sorteo")
                        .WithMany()
                        .HasForeignKey("SorteoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sorteo");
                });

            modelBuilder.Entity("eLotto.Core.Models.SorteosBoletos", b =>
                {
                    b.HasOne("eLotto.Core.Models.Sorteos", "Sorteos")
                        .WithMany("SorteosBoletos")
                        .HasForeignKey("SorteosId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sorteos");
                });

            modelBuilder.Entity("eLotto.Core.Models.SorteosRascaditoPremios", b =>
                {
                    b.HasOne("eLotto.Core.Models.Sorteos", "Sorteos")
                        .WithMany("RascaditoPremios")
                        .HasForeignKey("SorteosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sorteos");
                });

            modelBuilder.Entity("eLotto.Core.Models.SorteosRascaditos", b =>
                {
                    b.HasOne("eLotto.Core.Models.Sorteos", "Sorteos")
                        .WithMany("Rascaditos")
                        .HasForeignKey("SorteosId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eLotto.Core.Models.SorteosRascaditoPremios", "SorteosRascaditoPremio")
                        .WithMany()
                        .HasForeignKey("SorteosRascaditoPremioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eLotto.Core.Models.Users", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eLotto.Core.Models.WalletTransaction", "WalletTransactionOrigen")
                        .WithMany()
                        .HasForeignKey("WalletTransactionOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eLotto.Core.Models.WalletTransaction", "WalletTransactionPremio")
                        .WithOne()
                        .HasForeignKey("eLotto.Core.Models.SorteosRascaditos", "WalletTransactionPremioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sorteos");

                    b.Navigation("SorteosRascaditoPremio");

                    b.Navigation("Usuario");

                    b.Navigation("WalletTransactionOrigen");

                    b.Navigation("WalletTransactionPremio");
                });

            modelBuilder.Entity("eLotto.Core.Models.SorteosRascaditosGanadoresHistorial", b =>
                {
                    b.HasOne("eLotto.Core.Models.Sorteos", "Sorteo")
                        .WithMany()
                        .HasForeignKey("SorteoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eLotto.Core.Models.Users", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eLotto.Core.Models.WalletTransaction", "WalletTransactionOrigen")
                        .WithMany()
                        .HasForeignKey("WalletTransactionOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eLotto.Core.Models.WalletTransaction", "WalletTransactionPremio")
                        .WithMany()
                        .HasForeignKey("WalletTransactionPremioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sorteo");

                    b.Navigation("Usuario");

                    b.Navigation("WalletTransactionOrigen");

                    b.Navigation("WalletTransactionPremio");
                });

            modelBuilder.Entity("eLotto.Core.Models.UserWallet", b =>
                {
                    b.HasOne("eLotto.Core.Models.Users", "User")
                        .WithOne()
                        .HasForeignKey("eLotto.Core.Models.UserWallet", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("eLotto.Core.Models.WalletTransaction", b =>
                {
                    b.HasOne("eLotto.Core.Models.Sorteos", "Sorteo")
                        .WithMany()
                        .HasForeignKey("SorteoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eLotto.Core.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eLotto.Core.Models.UserWallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sorteo");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("eLotto.Core.Models.Sorteos", b =>
                {
                    b.Navigation("RascaditoPremios");

                    b.Navigation("Rascaditos");

                    b.Navigation("SorteosBoletos");
                });

            modelBuilder.Entity("eLotto.Core.Models.UserWallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
